TestCompletableFuture:
	mkdir -p build/Future
	javac -d build/Future Future/*.java
	cd build/Future && java TestCompletableFuture

TestThreadLocal:
	mkdir -p build/ThreadLocal
	javac -d build/ThreadLocal ThreadLocal/*.java
	cd build/ThreadLocal && java ThreadLocalDemo

clean:
	rm build/**/**.class